export const COUNTRIES = [
  { code: 'AU', name: 'Australia',       currency: 'AUD', timezone: 'Australia/Sydney'    },
  { code: 'AT', name: 'Austria',         currency: 'EUR', timezone: 'Europe/Vienna'       },
  { code: 'BE', name: 'Belgium',         currency: 'EUR', timezone: 'Europe/Brussels'     },
  { code: 'BR', name: 'Brazil',          currency: 'BRL', timezone: 'America/Sao_Paulo'   },
  { code: 'CA', name: 'Canada',          currency: 'CAD', timezone: 'America/Toronto'     },
  { code: 'CN', name: 'China',           currency: 'CNY', timezone: 'Asia/Shanghai'       },
  { code: 'CZ', name: 'Czech Republic',  currency: 'CZK', timezone: 'Europe/Prague'       },
  { code: 'DK', name: 'Denmark',         currency: 'DKK', timezone: 'Europe/Copenhagen'   },
  { code: 'FI', name: 'Finland',         currency: 'EUR', timezone: 'Europe/Helsinki'     },
  { code: 'FR', name: 'France',          currency: 'EUR', timezone: 'Europe/Paris'        },
  { code: 'DE', name: 'Germany',         currency: 'EUR', timezone: 'Europe/Berlin'       },
  { code: 'GH', name: 'Ghana',           currency: 'GHS', timezone: 'Africa/Accra'        },
  { code: 'HK', name: 'Hong Kong',       currency: 'HKD', timezone: 'Asia/Hong_Kong'      },
  { code: 'HU', name: 'Hungary',         currency: 'HUF', timezone: 'Europe/Budapest'     },
  { code: 'IN', name: 'India',           currency: 'INR', timezone: 'Asia/Kolkata'        },
  { code: 'ID', name: 'Indonesia',       currency: 'IDR', timezone: 'Asia/Jakarta'        },
  { code: 'IE', name: 'Ireland',         currency: 'EUR', timezone: 'Europe/Dublin'       },
  { code: 'IL', name: 'Israel',          currency: 'ILS', timezone: 'Asia/Jerusalem'      },
  { code: 'IT', name: 'Italy',           currency: 'EUR', timezone: 'Europe/Rome'         },
  { code: 'JP', name: 'Japan',           currency: 'JPY', timezone: 'Asia/Tokyo'          },
  { code: 'KE', name: 'Kenya',           currency: 'KES', timezone: 'Africa/Nairobi'      },
  { code: 'KR', name: 'South Korea',     currency: 'KRW', timezone: 'Asia/Seoul'          },
  { code: 'MY', name: 'Malaysia',        currency: 'MYR', timezone: 'Asia/Kuala_Lumpur'   },
  { code: 'MX', name: 'Mexico',          currency: 'MXN', timezone: 'America/Mexico_City' },
  { code: 'NL', name: 'Netherlands',     currency: 'EUR', timezone: 'Europe/Amsterdam'    },
  { code: 'NZ', name: 'New Zealand',     currency: 'NZD', timezone: 'Pacific/Auckland'    },
  { code: 'NG', name: 'Nigeria',         currency: 'NGN', timezone: 'Africa/Lagos'        },
  { code: 'NO', name: 'Norway',          currency: 'NOK', timezone: 'Europe/Oslo'         },
  { code: 'PK', name: 'Pakistan',        currency: 'PKR', timezone: 'Asia/Karachi'        },
  { code: 'PH', name: 'Philippines',     currency: 'PHP', timezone: 'Asia/Manila'         },
  { code: 'PL', name: 'Poland',          currency: 'PLN', timezone: 'Europe/Warsaw'       },
  { code: 'PT', name: 'Portugal',        currency: 'EUR', timezone: 'Europe/Lisbon'       },
  { code: 'RO', name: 'Romania',         currency: 'RON', timezone: 'Europe/Bucharest'    },
  { code: 'SG', name: 'Singapore',       currency: 'SGD', timezone: 'Asia/Singapore'      },
  { code: 'ZA', name: 'South Africa',    currency: 'ZAR', timezone: 'Africa/Johannesburg' },
  { code: 'ES', name: 'Spain',           currency: 'EUR', timezone: 'Europe/Madrid'       },
  { code: 'LK', name: 'Sri Lanka',       currency: 'LKR', timezone: 'Asia/Colombo'        },
  { code: 'SE', name: 'Sweden',          currency: 'SEK', timezone: 'Europe/Stockholm'    },
  { code: 'CH', name: 'Switzerland',     currency: 'CHF', timezone: 'Europe/Zurich'       },
  { code: 'TW', name: 'Taiwan',          currency: 'TWD', timezone: 'Asia/Taipei'         },
  { code: 'TH', name: 'Thailand',        currency: 'THB', timezone: 'Asia/Bangkok'        },
  { code: 'TR', name: 'Turkey',          currency: 'TRY', timezone: 'Europe/Istanbul'     },
  { code: 'UA', name: 'Ukraine',         currency: 'UAH', timezone: 'Europe/Kyiv'         },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED', timezone: 'Asia/Dubai'    },
  { code: 'GB', name: 'United Kingdom',  currency: 'GBP', timezone: 'Europe/London'      },
  { code: 'US', name: 'United States',   currency: 'USD', timezone: 'America/New_York'   },
  { code: 'VN', name: 'Vietnam',         currency: 'VND', timezone: 'Asia/Ho_Chi_Minh'   },
] as const satisfies readonly { code: string; name: string; currency: string; timezone: string }[]

export const CURRENCIES = [
  { code: 'AED', name: 'UAE Dirham',          symbol: 'د.إ' },
  { code: 'AUD', name: 'Australian Dollar',   symbol: 'A$'  },
  { code: 'BRL', name: 'Brazilian Real',      symbol: 'R$'  },
  { code: 'CAD', name: 'Canadian Dollar',     symbol: 'CA$' },
  { code: 'CHF', name: 'Swiss Franc',         symbol: 'Fr'  },
  { code: 'CNY', name: 'Chinese Yuan',        symbol: '¥'   },
  { code: 'CZK', name: 'Czech Koruna',        symbol: 'Kč'  },
  { code: 'DKK', name: 'Danish Krone',        symbol: 'kr'  },
  { code: 'EUR', name: 'Euro',                symbol: '€'   },
  { code: 'GBP', name: 'British Pound',       symbol: '£'   },
  { code: 'GHS', name: 'Ghanaian Cedi',       symbol: '₵'   },
  { code: 'HKD', name: 'Hong Kong Dollar',    symbol: 'HK$' },
  { code: 'HUF', name: 'Hungarian Forint',    symbol: 'Ft'  },
  { code: 'IDR', name: 'Indonesian Rupiah',   symbol: 'Rp'  },
  { code: 'ILS', name: 'Israeli Shekel',      symbol: '₪'   },
  { code: 'INR', name: 'Indian Rupee',        symbol: '₹'   },
  { code: 'JPY', name: 'Japanese Yen',        symbol: '¥'   },
  { code: 'KES', name: 'Kenyan Shilling',     symbol: 'KSh' },
  { code: 'KRW', name: 'South Korean Won',    symbol: '₩'   },
  { code: 'LKR', name: 'Sri Lankan Rupee',   symbol: 'Rs'  },
  { code: 'MXN', name: 'Mexican Peso',        symbol: '$'   },
  { code: 'MYR', name: 'Malaysian Ringgit',   symbol: 'RM'  },
  { code: 'NGN', name: 'Nigerian Naira',      symbol: '₦'   },
  { code: 'NOK', name: 'Norwegian Krone',     symbol: 'kr'  },
  { code: 'NZD', name: 'New Zealand Dollar',  symbol: 'NZ$' },
  { code: 'PHP', name: 'Philippine Peso',     symbol: '₱'   },
  { code: 'PKR', name: 'Pakistani Rupee',     symbol: '₨'   },
  { code: 'PLN', name: 'Polish Złoty',        symbol: 'zł'  },
  { code: 'RON', name: 'Romanian Leu',        symbol: 'lei' },
  { code: 'SEK', name: 'Swedish Krona',       symbol: 'kr'  },
  { code: 'SGD', name: 'Singapore Dollar',    symbol: 'S$'  },
  { code: 'THB', name: 'Thai Baht',           symbol: '฿'   },
  { code: 'TRY', name: 'Turkish Lira',        symbol: '₺'   },
  { code: 'TWD', name: 'Taiwan Dollar',       symbol: 'NT$' },
  { code: 'UAH', name: 'Ukrainian Hryvnia',   symbol: '₴'   },
  { code: 'USD', name: 'US Dollar',           symbol: '$'   },
  { code: 'VND', name: 'Vietnamese Dong',     symbol: '₫'   },
  { code: 'ZAR', name: 'South African Rand',  symbol: 'R'   },
] as const satisfies readonly { code: string; name: string; symbol: string }[]

export const TIMEZONES: { value: string; label: string }[] = [
  { value: 'Pacific/Midway',       label: '(UTC-11:00) Midway Island' },
  { value: 'Pacific/Honolulu',     label: '(UTC-10:00) Hawaii' },
  { value: 'America/Anchorage',    label: '(UTC-09:00) Alaska' },
  { value: 'America/Los_Angeles',  label: '(UTC-08:00) Pacific Time (US & Canada)' },
  { value: 'America/Denver',       label: '(UTC-07:00) Mountain Time (US & Canada)' },
  { value: 'America/Chicago',      label: '(UTC-06:00) Central Time (US & Canada)' },
  { value: 'America/New_York',     label: '(UTC-05:00) Eastern Time (US & Canada)' },
  { value: 'America/Halifax',      label: '(UTC-04:00) Atlantic Time (Canada)' },
  { value: 'America/Sao_Paulo',    label: '(UTC-03:00) Brasilia' },
  { value: 'Atlantic/South_Georgia', label: '(UTC-02:00) Mid-Atlantic' },
  { value: 'Atlantic/Azores',      label: '(UTC-01:00) Azores' },
  { value: 'UTC',                  label: '(UTC+00:00) UTC' },
  { value: 'Europe/London',        label: '(UTC+00:00) London' },
  { value: 'Europe/Paris',         label: '(UTC+01:00) Paris, Berlin, Rome' },
  { value: 'Europe/Helsinki',      label: '(UTC+02:00) Helsinki, Kyiv' },
  { value: 'Europe/Moscow',        label: '(UTC+03:00) Moscow' },
  { value: 'Asia/Dubai',           label: '(UTC+04:00) Dubai' },
  { value: 'Asia/Karachi',         label: '(UTC+05:00) Karachi, Islamabad' },
  { value: 'Asia/Colombo',         label: '(UTC+05:30) Sri Lanka' },
  { value: 'Asia/Dhaka',           label: '(UTC+06:00) Dhaka' },
  { value: 'Asia/Bangkok',         label: '(UTC+07:00) Bangkok, Jakarta' },
  { value: 'Asia/Singapore',       label: '(UTC+08:00) Singapore, KL' },
  { value: 'Asia/Tokyo',           label: '(UTC+09:00) Tokyo, Seoul' },
  { value: 'Australia/Sydney',     label: '(UTC+10:00) Sydney' },
  { value: 'Pacific/Auckland',     label: '(UTC+12:00) Auckland' },
]
